{{- if and .Values.secret.dbSecret.enabled (not .Values.aws.secretmanager.enabled) (not .Values.azure.keyvault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.name" . }}-dbsecret
  namespace: {{ .Values.namespaces.nexusNs }}
  labels:
{{ include "nexus.labels" . | indent 4 }}
  {{- if .Values.nexus.extraLabels }}
    {{- with .Values.nexus.extraLabels }}
      {{ toYaml . | indent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
stringData:
  db-host: {{ .Values.secret.db.host }}
  db-user: {{ .Values.secret.db.user }}
  db-password: {{ .Values.secret.db.password }}
{{- end }}
