{{- if .Values.nexus.docker.enabled }}
{{- if .Values.nexus.docker.createIngress }}
{{- $fullName := include "nexus.fullname" . -}}
{{- range $registry := .Values.nexus.docker.registries }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ default $.Release.Namespace $.Values.namespaces.nexusNs.name | quote }}
  name: {{ $fullName | trunc 49 }}-docker-{{ $registry.port }}
  labels:
    {{- include "nexus.labels" $ | nindent 4 }}
    {{- if $.Values.nexus.extraLabels }}
      {{- with $.Values.nexus.extraLabels }}
        {{ toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
  {{- with $registry.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.ingress.ingressClassName }}
  ingressClassName: {{ $.Values.ingress.ingressClassName }}
  {{ end }}
  {{- if $registry.enableTLS }}
  tls:
    - hosts:
        - {{ $registry.host | quote }}
      secretName: {{ $registry.secretName }}
  {{ end }}
  rules:
    - host: {{ $registry.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName | trunc 49 }}-docker-{{ $registry.port }}
                port:
                  number: {{ $registry.port }}
---
{{ end }}
{{ end }}
{{ end }}
