{{- if and (not .Values.aws.secretmanager.enabled) (not .Values.azure.keyvault.enabled) (not .Values.secret.nexusAdminSecret.enabled) }}
{{- if .Values.externalsecrets.enabled  }}
apiVersion: {{ .Values.externalsecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ template "nexus.name" . }}-external-adminsecret
  namespace: {{ .Values.namespaces.nexusNs.name }}
  labels: {{- include "nexus.labels" . | nindent 4 }}
  {{- if .Values.nexus.extraLabels }}
    {{- with .Values.nexus.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalsecrets.secrets.admin.refreshInterval }}
  secretStoreRef:
    kind: SecretStore
    name: {{ template "nexus.name" . }}-{{ .Values.externalsecrets.secretstore.name }}
  target:
    name: {{ template "nexus.name" . }}-adminsecret
    creationPolicy: Owner
  data:
    - secretKey: nexus-admin-password
      remoteRef:
        {{- if .Values.externalsecrets.secrets.admin.valueIsJson }}
        key: {{ .Values.externalsecrets.secrets.admin.providerSecretName }}
        property: {{ .Values.externalsecrets.secrets.admin.adminPasswordKey }}
        {{ else }}
        key: {{ .Values.externalsecrets.secrets.admin.adminPasswordKey }}
        {{- end }}
{{- end }}
{{- end }}

