{{- if and (.Values.statefulset.imagePullSecrets) (not (kindIs "slice" .Values.statefulset.imagePullSecretst)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.name" . }}-imagepullsecret
  namespace: {{ .Values.namespaces.nexusNs.name }}
  labels:
  {{- include "nexus.labels" . | nindent 4 }}
    {{- if .Values.nexus.extraLabels }}
      {{- with .Values.nexus.extraLabels }}
        {{ toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
data:
  .dockerconfigjson: {{ required "A valid .Values.statefulset.imagePullSecrets.secret is required!" .Values.statefulset.imagePullSecrets.secret }}

type: kubernetes.io/dockerconfigjson
{{- end }}
