{{- if .Values.secret.license.licenseSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.license.name }}
  namespace: {{ .Values.namespaces.nexusNs.name }}
  labels:
{{ include "nexus.labels" . | nindent 4 }}
  {{- if .Values.nexus.extraLabels }}
    {{- with .Values.nexus.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{ .Values.secret.license.name }}: |-
    {{ .Values.secret.license.licenseSecret.fileContentsBase64 }}
{{- end }}
