{{- if and .Values.secret.license.licenseSecret.enabled (not .Values.azure.keyvault.enabled) (not .Values.aws.secretmanager.enabled) (not .Values.externalsecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.license.name }}
  namespace: {{ default .Release.Namespace .Values.namespaces.nexusNs.name | quote }}
  labels:
{{ include "nexus.labels" . | nindent 4 }}
  {{- if .Values.nexus.extraLabels }}
    {{- with .Values.nexus.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
{{- if .Values.secret.license.licenseSecret.file }}
data:
  {{ .Values.secret.license.name }}: {{ .Values.secret.license.licenseSecret.file | b64enc }}
{{ else if .Values.secret.license.licenseSecret.fileContentsBase64 }}  
data:
  {{ .Values.secret.license.name }}: |-
    {{ .Values.secret.license.licenseSecret.fileContentsBase64 }}
{{- end }}
{{- end }}
