{{- if .Values.namespaces.nexusNs.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ default .Release.Namespace .Values.namespaces.nexusNs.name | quote }}
{{- end }}
---
{{- if .Values.aws.enabled }}
{{- if .Values.namespaces.cloudwatchNs.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.cloudwatchNs.name | quote}}
{{- end }}
---
{{- if .Values.aws.externaldns.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.externaldnsNs | quote }}
{{- end }}
---
{{- end }}