{{- if .Values.namespaces.nexusNs.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.nexusNs.name }}
{{- end }}
---
{{- if .Values.aws.enabled }}
{{- if .Values.namespaces.cloudwatchNs.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.cloudwatchNs.name }}
{{- end }}
---
{{- if .Values.aws.externaldns.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.externaldnsNs }}
{{- end }}
---
{{- end }}