{{- if and .Values.secret.nexusAdminSecret.enabled (not .Values.aws.secretmanager.enabled) (not .Values.azure.keyvault.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nexus.name" . }}-adminsecret
  namespace: {{ .Values.namespaces.nexusNs }}
  labels:
  {{- include "nexus.labels" . | nindent 4 }}
    {{- if .Values.nexus.extraLabels }}
      {{- with .Values.nexus.extraLabels }}
        {{ toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
type: Opaque
stringData:
  nexus-admin-password: {{ .Values.secret.nexusAdminSecret.adminPassword }}
{{- end }}
