{{- if and .Values.secret.nexusSecret.enabled (not .Values.secret.aws.nexusSecret.enabled ) (not .Values.secret.azure.nexusSecret.enabled) (not .Values.externalsecrets.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.nexusSecret.name }}
  namespace: {{ default .Release.Namespace .Values.namespaces.nexusNs.name | quote }}
  labels:
{{ include "nexus.labels" . | nindent 4 }}
  {{- if .Values.nexus.extraLabels }}
    {{- with .Values.nexus.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  {{ .Values.secret.nexusSecret.name }}: {{ .Values.secret.nexusSecret.secretKeyfile | b64enc }}
{{- end }}
