{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nexus.serviceAccountName" . }}
  namespace: {{ default .Release.Namespace .Values.namespaces.nexusNs.name | quote }}
  labels: {{- include "nexus.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.labels }}
    {{- with .Values.serviceAccount.labels}}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if .Values.nexus.extraLabels }}
    {{- with .Values.nexus.extraLabels }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
